# Development
services:
  server:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
